### PR TITLE
DEBUG: in the readme the order of the parameters was wrong, this way it ...

### PR DESCRIPTION
**Pull request by tattish**
Chaned the order of the params in the readme, while in the original one, it is wrong:
the HOST:PORT/DB should be the first one otherwise it will not be parsed.

### CODE REVIEW

**Comment by devkev** [comment]
Thanks for catching this oversight @tattish.  You're right that the `HOST:PORT/DB` parameter needs to come earlier on the line, but it actually only needs to come before the first `.js` file.  However, that said, I also prefer how you have it here - right at the start where it (and the auth parameters) are most visible.

:+1:

**Comment by jamestyj** [comment]
LGTM

**Comment by braz** [comment]
LGTM as well

**Comment by tattish** [comment]
I accidentally committed something else also (somewhat solution for #22 ), but it worth to look at before merging with the previous. Let me know if you like it or not. And sorry for messing up the two things.

**Comment by jribnik** [comment]
lgtm

**Comment by ntang** [comment]
@tattish looks fine to me, I merged both in.  Thanks for the submission!

**Pull request merged**
